In [4]:
import pandas as pd
import json

In [5]:
from google.colab import files
uploaded = files.upload()

In [17]:
import pandas as pd
import json

# Load the JSON file
with open('/content/DataEngineeringQ2.json') as file:
    data = json.load(file)

# Normalize the JSON data
df = pd.json_normalize(data, sep='_')

In [31]:
df

,_id,appointmentId,phoneNumber,patientDetails__id,patientDetails_firstName,patientDetails_lastName,patientDetails_emailId,patientDetails_gender,patientDetails_alternateContact,patientDetails_birthDate,...,consultationData_procedures,consultationData_prognosis,consultationData_sharePrescription,patientDetails_phrId,patientDetails_chat__id,patientDetails_customId,patientDetails_chat_channelId,consultationData__id,consultationData_updatedAt,consultationData_createdAt
0,T6hf3rb5,40d2-9c9f,96686896670,T6hb630b3,Css,,,,,None,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,T65g3rb5,40dbtc9f,9496368916,T6h33b300,Lokesh,,,M,NaN,1996-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,T7g6Srb5,g3Wt5c9f,7787204833,TjhB4373,Shila,Das,,NaN,NaN,NaN,...,[],[],False,63b5hvy614d5,NaN,NaN,NaN,NaN,NaN,NaN
3,94bg8W8d,fb6-a535,9376756879,6df4R5b,Bhavika,Ben Panchal,,F,NaN,1988-04-24T14:30:00.000Z,...,[],[],False,644nig7y,NaN,NaN,NaN,NaN,NaN,NaN
4,T6h8H56c,67h7KL9,5267384241,lK9hy06a,Raghu Viju,,,NaN,,NaN,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,T9Jh8c8,Hy7Y91,+919826374025,kI9d5c6,Dinesh Kumar,,,M,NaN,1983-05-16T18:30:00.000Z,...,[],[],False,NaN,09hUb5c7,3FPEUCW8HACJ,NaN,NaN,NaN,NaN
6,9Is624b9,10dY8a-4a,7587265252,i9R324b7,Lalit,Sankhwal,,M,,2003-06-27T14:30:00.000Z,...,[],[],False,67Yt2b97,NaN,NaN,NaN,NaN,NaN,NaN
7,T8H9c3c6,e8056Ye8,5586958767,T6h41b5ad3d8002ad9c3c4,Ravi,,,NaN,NaN,NaN,...,[],[],False,NaN,T6h41b5ad3d8002ad9c3c5,8AV4ICI5I389,NaN,NaN,NaN,NaN
8,T8Ud380,dbc0-c66b,9987602525,T9Iy347e,Dinesh,,,M,NaN,1983-05-16T18:30:00.000Z,...,[],[],False,NaN,T9IsT37f,0308MSAHYR8K,NaN,NaN,NaN,NaN
9,T345fG4,1576a7,9234354366,T4Rb1a2,Sanjay,,,M,NaN,1998-05-16T18:30:00.000Z,...,[],[],False,NaN,7Yd9b1a3,8S7A3D4K4WZH,NaN,NaN,NaN,NaN
10,T4F6a175,b6Te4ac,4863281056,Tr4T2173,Akshay,Akshay,,M,NaN,1988-04-08T00:00:00.000Z,...,[],[],False,6E48U79,Tr4W174,83AH0K04SSTV,9IrR9ce7,NaN,NaN,NaN
11,TW3r002,bu5Qfb,8687986800,T6Wa50,Nirmala,,,F,NaN,1971-05-16T18:30:00.000Z,...,[],[],False,NaN,T6h3635ad3d8002ad9b001,832ZIS6ZCAHH,NaN,NaN,NaN,NaN
12,6U6Ra36,86U8Y45,,65sRa36,Satish,,,NaN,NaN,1970-05-16T18:30:00.000Z,...,[],[],False,NaN,6Y6a36,YW883CARSES3,NaN,NaN,NaN,NaN
13,u7Y7Aa5,Ufd7231,7152684236,UG67231,Kalaiarasi,Kalaiarasi,,F,,1997-07-31T00:00:00.000Z,...,[],[],False,T6a7231,NaN,NaN,NaN,6T67a6a4,2023-05-16T14:42:50.620Z,2023-05-16T14:42:50.620Z
14,T3R5dec,E4u5Ea2,,E4u5Ea2,Satyanaaryan,,,NaN,,NaN,...,[],[],False,NaN,E4u5Ea2,E4u5Ea2,NaN,NaN,NaN,NaN
15,T4E7Ge6,T4E3e410,9184723620,T4E7Ge6,Nivitha,,,F,NaN,1997-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,E5336545,04Re22d,,04Re22d,Tejpal,,,M,NaN,1972-05-16T18:30:00.000Z,...,[],[],False,NaN,04Re22d,04Re22d,NaN,NaN,NaN,NaN
17,T7Ys58b,af9784hf,5847346075,u7dWa589,Nandhini,,,F,NaN,2001-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Y874Us5w,I8eW201,9064537237,TU7e913,Dhanamma,,,F,NaN,NaN,...,[],[],False,NaN,u8e6fgd14,y7ewr5w,NaN,NaN,NaN,NaN
19,Y7s5G42,f7r501cb1,,H8s2d40,Kushal,,,NaN,NaN,NaN,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Y7eE5cd8,cf092c8t6c,992727892,u9cd6,Daniya,Zehra,,F,NaN,2001-08-27T00:00:00.000Z,...,[],[],False,6463U8s231,NaN,NaN,NaN,NaN,NaN,NaN
21,I9984e8,O02n262e,6888324121,Pdh97S6,Jay,Sharma,,M,NaN,1998-11-19T23:30:00.000Z,...,[],[],False,Jus0480,NaN,NaN,NaN,NaN,NaN,NaN
22,Tu78a783,5dfN9s41,8248594521,h02U8a781,Preethi,,,F,NaN,1996-05-16T18:30:00.000Z,...,[],[],False,NaN,T6h9a782,H8NdI3MAW,NaN,NaN,NaN,NaN
23,U9D2w6c,cc86re0f,+917938475936,T6h40a5ad3d8002ad9c06a,VITTHAL SHANKARRAO GHATE,,NaN,NaN,+917797689682,NaN,...,[],[],False,NaN,T6h40a1becc5002908b235,83AAWWI24W63,NaN,NaN,NaN,NaN
24,T6hY6sEe,bd99dU7,+9124648979746,Y7sHec,Naresh,,,M,NaN,1992-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,H7sT6c,bcWe50,+916883788633,T6h408981ayf32b63bcfa,Suresh,Gaikwad,,NaN,,NaN,...,[],[],False,NaN,Hsb690S,ABCD1419,NaN,NaN,NaN,NaN
26,8Utyd5b,7au8se3,+916636278363,T6U67af9,Govardhan,,,NaN,,NaN,...,[],[],False,NaN,u7sg9be5a,Gya7sfw,NaN,NaN,NaN,NaN
27,y87Ta5c7,432cT213,6525356535,R53Et5W,Rajeshwari,,,F,NaN,1999-05-16T18:30:00.000Z,...,[],[],False,NaN,T6h2fT5535c6,K44RwH0T,NaN,NaN,NaN,NaN
28,Ub7S65b7,D3fFr42c,,dE3r$2b5,Santosh,,,F,NaN,1972-05-16T18:30:00.000Z,...,[],[],False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,yD7s2d7,7uyT6Rs,+919093872282,TI93Hd5,Tarachand,,,M,,1980-03-22T18:30:00.000Z,...,[],[],False,NaN,TH8W2d6,90hjdX2,NaN,NaN,NaN,NaN
30,I9Sb4e8,O02n2e,+916888324121,Pdh97S6,Jay,Sharma,,M,NaN,1991-11-19T23:30:00.000Z,...,[],[],False,Jus0480,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
patient_details_list = [item['patientDetails'] for item in data]

In [20]:
# Convert the list to a DataFrame
patient_details = pd.DataFrame(patient_details_list)

In [30]:
patient_details

,_id,firstName,lastName,emailId,gender,alternateContact,birthDate,phrId,chat,customId,age,ageGroup
0,T6hb630b3,Css,,,M,,NaT,NaN,NaN,NaN,NaN,Senior
1,T6h33b300,Lokesh,,,M,NaN,1996-05-16 18:30:00+00:00,NaN,NaN,NaN,28.0,Adult
2,TjhB4373,Shila,Das,,M,NaN,NaT,63b5hvy614d5,NaN,NaN,NaN,Senior
3,6df4R5b,Bhavika,Ben Panchal,,F,NaN,1988-04-24 14:30:00+00:00,644nig7y,NaN,NaN,36.0,Adult
4,lK9hy06a,Raghu Viju,,,M,,NaT,NaN,NaN,NaN,NaN,Senior
5,kI9d5c6,Dinesh Kumar,,,M,NaN,1983-05-16 18:30:00+00:00,NaN,{'_id': '09hUb5c7'},3FPEUCW8HACJ,41.0,Adult
6,i9R324b7,Lalit,Sankhwal,,M,,2003-06-27 14:30:00+00:00,67Yt2b97,NaN,NaN,21.0,Adult
7,T6h41b5ad3d8002ad9c3c4,Ravi,,,M,NaN,NaT,NaN,{'_id': 'T6h41b5ad3d8002ad9c3c5'},8AV4ICI5I389,NaN,Senior
8,T9Iy347e,Dinesh,,,M,NaN,1983-05-16 18:30:00+00:00,NaN,{'_id': 'T9IsT37f'},0308MSAHYR8K,41.0,Adult
9,T4Rb1a2,Sanjay,,,M,NaN,1998-05-16 18:30:00+00:00,NaN,{'_id': '7Yd9b1a3'},8S7A3D4K4WZH,26.0,Adult
10,Tr4T2173,Akshay,Akshay,,M,NaN,1988-04-08 00:00:00+00:00,6E48U79,"{'_id': 'Tr4W174', 'channelId': '9IrR9ce7'}",83AH0K04SSTV,36.0,Adult
11,T6Wa50,Nirmala,,,F,NaN,1971-05-16 18:30:00+00:00,NaN,{'_id': 'T6h3635ad3d8002ad9b001'},832ZIS6ZCAHH,53.0,Adult
12,65sRa36,Satish,,,M,NaN,1970-05-16 18:30:00+00:00,NaN,{'_id': '6Y6a36'},YW883CARSES3,54.0,Adult
13,UG67231,Kalaiarasi,Kalaiarasi,,F,,1997-07-31 00:00:00+00:00,T6a7231,NaN,NaN,27.0,Adult
14,E4u5Ea2,Satyanaaryan,,,M,,NaT,NaN,{'_id': 'E4u5Ea2'},E4u5Ea2,NaN,Senior
15,T4E7Ge6,Nivitha,,,F,NaN,1997-05-16 18:30:00+00:00,NaN,NaN,NaN,27.0,Adult
16,04Re22d,Tejpal,,,M,NaN,1972-05-16 18:30:00+00:00,NaN,{'_id': '04Re22d'},04Re22d,52.0,Adult
17,u7dWa589,Nandhini,,,F,NaN,2001-05-16 18:30:00+00:00,NaN,NaN,NaN,23.0,Adult
18,TU7e913,Dhanamma,,,F,NaN,NaT,NaN,{'_id': 'u8e6fgd14'},y7ewr5w,NaN,Senior
19,H8s2d40,Kushal,,,M,NaN,NaT,NaN,NaN,NaN,NaN,Senior
20,u9cd6,Daniya,Zehra,,F,NaN,2001-08-27 00:00:00+00:00,6463U8s231,NaN,NaN,23.0,Adult
21,Pdh97S6,Jay,Sharma,,M,NaN,1998-11-19 23:30:00+00:00,Jus0480,NaN,NaN,26.0,Adult
22,h02U8a781,Preethi,,,F,NaN,1996-05-16 18:30:00+00:00,NaN,{'_id': 'T6h9a782'},H8NdI3MAW,28.0,Adult
23,T6h40a5ad3d8002ad9c06a,VITTHAL SHANKARRAO GHATE,,NaN,M,+917797689682,NaT,NaN,{'_id': 'T6h40a1becc5002908b235'},83AAWWI24W63,NaN,Senior
24,Y7sHec,Naresh,,,M,NaN,1992-05-16 18:30:00+00:00,NaN,NaN,NaN,32.0,Adult
25,T6h408981ayf32b63bcfa,Suresh,Gaikwad,,M,,NaT,NaN,{'_id': 'Hsb690S'},ABCD1419,NaN,Senior
26,T6U67af9,Govardhan,,,M,,NaT,NaN,{'_id': 'u7sg9be5a'},Gya7sfw,NaN,Senior
27,R53Et5W,Rajeshwari,,,F,NaN,1999-05-16 18:30:00+00:00,NaN,{'_id': 'T6h2fT5535c6'},K44RwH0T,25.0,Adult
28,dE3r$2b5,Santosh,,,F,NaN,1972-05-16 18:30:00+00:00,NaN,NaN,NaN,52.0,Adult
29,TI93Hd5,Tarachand,,,M,,1980-03-22 18:30:00+00:00,NaN,{'_id': 'TH8W2d6'},90hjdX2,44.0,Adult
30,Pdh97S6,Jay,Sharma,,M,NaN,1991-11-19 23:30:00+00:00,Jus0480,NaN,NaN,33.0,Adult

In [14]:
def missing_percentage(column):
    total = len(df)
    missing = df[column].apply(lambda x: x == '').sum()
    return round((missing / total) * 100, 2)

In [21]:

def missing_percentage(column):
    total = len(patient_details)
    missing = patient_details[column].apply(lambda x: x == '' or pd.isnull(x)).sum()
    return round((missing / total) * 100, 2)


missing_percentages = {
    'firstName': missing_percentage('firstName'),
    'lastName': missing_percentage('lastName'),
    'DOB': missing_percentage('birthDate')
}

missing_percentages

{'firstName': 0.0, 'lastName': 70.97, 'DOB': 32.26}

In [22]:

mode_gender = patient_details['gender'].mode()[0]

patient_details['gender'].replace('', mode_gender, inplace=True)
patient_details['gender'].fillna(mode_gender, inplace=True)

In [23]:

total = len(patient_details)
female_count = (patient_details['gender'] == 'Female').sum()
female_percentage = round((female_count / total) * 100, 2)

In [24]:
female_percentage

0.0

In [25]:
import datetime

patient_details['birthDate'] = pd.to_datetime(patient_details['birthDate'], errors='coerce')

current_year = datetime.datetime.now().year
patient_details['age'] = patient_details['birthDate'].apply(lambda x: current_year - x.year if pd.notnull(x) else None)

In [26]:

def categorize_age(age):
    if age is None:
        return 'Unknown'
    elif age <= 12:
        return 'Child'
    elif 13 <= age <= 19:
        return 'Teen'
    elif 20 <= age <= 59:
        return 'Adult'
    else:
        return 'Senior'

patient_details['ageGroup'] = patient_details['age'].apply(categorize_age)

In [27]:

adult_count = patient_details[patient_details['ageGroup'] == 'Adult'].shape[0]
adult_count

21

In [40]:
df['num_medicines'] = df['consultationData_medicines'].apply(lambda x: len(x) if isinstance(x, list) else 0)

In [41]:
average_medicines = df['num_medicines'].mean()

average_medicines_rounded = round(average_medicines, 2)

average_medicines_rounded

2.13

In [39]:
patient_details.columns

Index(['_id', 'firstName', 'lastName', 'emailId', 'gender', 'alternateContact',
       'birthDate', 'phrId', 'chat', 'customId', 'age', 'ageGroup'],
      dtype='object')

In [37]:
df.columns

Index(['_id', 'appointmentId', 'phoneNumber', 'patientDetails__id',
       'patientDetails_firstName', 'patientDetails_lastName',
       'patientDetails_emailId', 'patientDetails_gender',
       'patientDetails_alternateContact', 'patientDetails_birthDate',
       'consultationData_adviceTemplates', 'consultationData_advices',
       'consultationData_attachments', 'consultationData_chiefComplaints',
       'consultationData_customOne', 'consultationData_customThree',
       'consultationData_customTwo', 'consultationData_disease',
       'consultationData_doctorNotes',
       'consultationData_emergencyInstructions',
       'consultationData_emergencyInstructionsTemplate',
       'consultationData_emrTemplates', 'consultationData_examinationNote',
       'consultationData_findings',
       'consultationData_investigationInstructions',
       'consultationData_investigationTemplates',
       'consultationData_investigations',
       'consultationData_isBalicAppointment',
       'consultationData_isQuickPrescription', 'consultationData_labTest',
       'consultationData_languageCode', 'consultationData_medicineTemplates',
       'consultationData_medicines', 'consultationData_procedures',
       'consultationData_prognosis', 'consultationData_sharePrescription',
       'patientDetails_phrId', 'patientDetails_chat__id',
       'patientDetails_customId', 'patientDetails_chat_channelId',
       'consultationData__id', 'consultationData_updatedAt',
       'consultationData_createdAt'],
      dtype='object')

In [34]:
print(df.head)

<bound method NDFrame.head of          _id appointmentId     phoneNumber      patientDetails__id  \
0   T6hf3rb5     40d2-9c9f     96686896670               T6hb630b3
1   T65g3rb5      40dbtc9f      9496368916               T6h33b300
2   T7g6Srb5      g3Wt5c9f      7787204833                TjhB4373
3   94bg8W8d      fb6-a535      9376756879                 6df4R5b
4   T6h8H56c       67h7KL9      5267384241                lK9hy06a
5    T9Jh8c8        Hy7Y91   +919826374025                 kI9d5c6
6   9Is624b9     10dY8a-4a      7587265252                i9R324b7
7   T8H9c3c6      e8056Ye8      5586958767  T6h41b5ad3d8002ad9c3c4
8    T8Ud380     dbc0-c66b      9987602525                T9Iy347e
9    T345fG4        1576a7      9234354366                 T4Rb1a2
10  T4F6a175       b6Te4ac      4863281056                Tr4T2173
11   TW3r002        bu5Qfb      8687986800                  T6Wa50
12   6U6Ra36       86U8Y45                                 65sRa36
13   u7Y7Aa5       Ufd7231      7152684236                 UG67231
14   T3R5dec       E4u5Ea2                                 E4u5Ea2
15   T4E7Ge6      T4E3e410      9184723620                 T4E7Ge6
16  E5336545       04Re22d                                 04Re22d
17   T7Ys58b      af9784hf      5847346075                u7dWa589
18  Y874Us5w       I8eW201      9064537237                 TU7e913
19   Y7s5G42     f7r501cb1                                 H8s2d40
20  Y7eE5cd8    cf092c8t6c       992727892                   u9cd6
21   I9984e8      O02n262e      6888324121                 Pdh97S6
22  Tu78a783      5dfN9s41      8248594521               h02U8a781
23   U9D2w6c      cc86re0f   +917938475936  T6h40a5ad3d8002ad9c06a
24  T6hY6sEe       bd99dU7  +9124648979746                  Y7sHec
25    H7sT6c        bcWe50   +916883788633   T6h408981ayf32b63bcfa
26   8Utyd5b       7au8se3   +916636278363                T6U67af9
27  y87Ta5c7      432cT213      6525356535                 R53Et5W
28  Ub7S65b7      D3fFr42c                                dE3r$2b5
29   yD7s2d7       7uyT6Rs   +919093872282                 TI93Hd5
30   I9Sb4e8        O02n2e   +916888324121                 Pdh97S6

    patientDetails_firstName patientDetails_lastName patientDetails_emailId  \
0                        Css
1                     Lokesh
2                      Shila                     Das
3                    Bhavika             Ben Panchal
4                 Raghu Viju
5               Dinesh Kumar
6                      Lalit                Sankhwal
7                       Ravi
8                     Dinesh
9                     Sanjay
10                    Akshay                  Akshay
11                   Nirmala
12                    Satish
13                Kalaiarasi              Kalaiarasi
14              Satyanaaryan
15                   Nivitha
16                    Tejpal
17                  Nandhini
18                  Dhanamma
19                    Kushal
20                    Daniya                   Zehra
21                       Jay                  Sharma
22                   Preethi
23  VITTHAL SHANKARRAO GHATE                                            NaN
24                    Naresh
25                    Suresh                 Gaikwad
26                 Govardhan
27                Rajeshwari
28                   Santosh
29                 Tarachand
30                       Jay                  Sharma

   patientDetails_gender patientDetails_alternateContact  \
0
1                      M                             NaN
2                    NaN                             NaN
3                      F                             NaN
4                    NaN
5                      M                             NaN
6                      M
7                    NaN                             NaN
8                      M                             NaN
9                      M                             NaN
10                     M                             NaN
11                     F                             NaN
12                   NaN                             NaN
13                     F
14                   NaN
15                     F                             NaN
16                     M                             NaN
17                     F                             NaN
18                     F                             NaN
19                   NaN                             NaN
20                     F                             NaN
21                     M                             NaN
22                     F                             NaN
23                   NaN                   +917797689682
24                     M                             NaN
25                   NaN
26                   NaN
27                     F                             NaN
28                     F                             NaN
29                     M
30                     M                             NaN

    patientDetails_birthDate  ... consultationData_procedures  \
0                       None  ...                          []
1   1996-05-16T18:30:00.000Z  ...                          []
2                        NaN  ...                          []
3   1988-04-24T14:30:00.000Z  ...                          []
4                        NaN  ...                          []
5   1983-05-16T18:30:00.000Z  ...                          []
6   2003-06-27T14:30:00.000Z  ...                          []
7                        NaN  ...                          []
8   1983-05-16T18:30:00.000Z  ...                          []
9   1998-05-16T18:30:00.000Z  ...                          []
10  1988-04-08T00:00:00.000Z  ...                          []
11  1971-05-16T18:30:00.000Z  ...                          []
12  1970-05-16T18:30:00.000Z  ...                          []
13  1997-07-31T00:00:00.000Z  ...                          []
14                       NaN  ...                          []
15  1997-05-16T18:30:00.000Z  ...                          []
16  1972-05-16T18:30:00.000Z  ...                          []
17  2001-05-16T18:30:00.000Z  ...                          []
18                       NaN  ...                          []
19                       NaN  ...                          []
20  2001-08-27T00:00:00.000Z  ...                          []
21  1998-11-19T23:30:00.000Z  ...                          []
22  1996-05-16T18:30:00.000Z  ...                          []
23                       NaN  ...                          []
24  1992-05-16T18:30:00.000Z  ...                          []
25                       NaN  ...                          []
26                       NaN  ...                          []
27  1999-05-16T18:30:00.000Z  ...                          []
28  1972-05-16T18:30:00.000Z  ...                          []
29  1980-03-22T18:30:00.000Z  ...                          []
30  1991-11-19T23:30:00.000Z  ...                          []

   consultationData_prognosis consultationData_sharePrescription  \
0                          []                              False
1                          []                              False
2                          []                              False
3                          []                              False
4                          []                              False
5                          []                              False
6                          []                              False
7                          []                              False
8                          []                              False
9                          []                              False
10                         []                              False
11                         []                              False
12                         []                              False
13                         []                              False
14                         []                              False
15                         []                              False
16                         []                              False
17                         []                              False
18                         []                              False
19                         []                              False
20                         []                              False
21                         []                              False
22                         []                              False
23                         []                              False
24                         []                              False
25                         []                              False
26                         []                              False
27                         []                              False
28                         []                              False
29                         []                              False
30                         []                              False

   patientDetails_phrId patientDetails_chat__id patientDetails_customId  \
0                   NaN                     NaN                     NaN
1                   NaN                     NaN                     NaN
2          63b5hvy614d5                     NaN                     NaN
3              644nig7y                     NaN                     NaN
4                   NaN                     NaN                     NaN
5                   NaN                09hUb5c7            3FPEUCW8HACJ
6              67Yt2b97                     NaN                     NaN
7                   NaN  T6h41b5ad3d8002ad9c3c5            8AV4ICI5I389
8                   NaN                T9IsT37f            0308MSAHYR8K
9                   NaN                7Yd9b1a3            8S7A3D4K4WZH
10              6E48U79                 Tr4W174            83AH0K04SSTV
11                  NaN  T6h3635ad3d8002ad9b001            832ZIS6ZCAHH
12                  NaN                  6Y6a36            YW883CARSES3
13              T6a7231                     NaN                     NaN
14                  NaN                 E4u5Ea2                 E4u5Ea2
15                  NaN                     NaN                     NaN
16                  NaN                 04Re22d                 04Re22d
17                  NaN                     NaN                     NaN
18                  NaN               u8e6fgd14                 y7ewr5w
19                  NaN                     NaN                     NaN
20           6463U8s231                     NaN                     NaN
21              Jus0480                     NaN                     NaN
22                  NaN                T6h9a782               H8NdI3MAW
23                  NaN  T6h40a1becc5002908b235            83AAWWI24W63
24                  NaN                     NaN                     NaN
25                  NaN                 Hsb690S                ABCD1419
26                  NaN               u7sg9be5a                 Gya7sfw
27                  NaN            T6h2fT5535c6                K44RwH0T
28                  NaN                     NaN                     NaN
29                  NaN                 TH8W2d6                 90hjdX2
30              Jus0480                     NaN                     NaN

   patientDetails_chat_channelId consultationData__id  \
0                            NaN                  NaN
1                            NaN                  NaN
2                            NaN                  NaN
3                            NaN                  NaN
4                            NaN                  NaN
5                            NaN                  NaN
6                            NaN                  NaN
7                            NaN                  NaN
8                            NaN                  NaN
9                            NaN                  NaN
10                      9IrR9ce7                  NaN
11                           NaN                  NaN
12                           NaN                  NaN
13                           NaN             6T67a6a4
14                           NaN                  NaN
15                           NaN                  NaN
16                           NaN                  NaN
17                           NaN                  NaN
18                           NaN                  NaN
19                           NaN                  NaN
20                           NaN                  NaN
21                           NaN                  NaN
22                           NaN                  NaN
23                           NaN                  NaN
24                           NaN                  NaN
25                           NaN                  NaN
26                           NaN                  NaN
27                           NaN                  NaN
28                           NaN                  NaN
29                           NaN                  NaN
30                           NaN                  NaN

   consultationData_updatedAt consultationData_createdAt
0                         NaN                        NaN
1                         NaN                        NaN
2                         NaN                        NaN
3                         NaN                        NaN
4                         NaN                        NaN
5                         NaN                        NaN
6                         NaN                        NaN
7                         NaN                        NaN
8                         NaN                        NaN
9                         NaN                        NaN
10                        NaN                        NaN
11                        NaN                        NaN
12                        NaN                        NaN
13   2023-05-16T14:42:50.620Z   2023-05-16T14:42:50.620Z
14                        NaN                        NaN
15                        NaN                        NaN
16                        NaN                        NaN
17                        NaN                        NaN
18                        NaN                        NaN
19                        NaN                        NaN
20                        NaN                        NaN
21                        NaN                        NaN
22                        NaN                        NaN
23                        NaN                        NaN
24                        NaN                        NaN
25                        NaN                        NaN
26                        NaN                        NaN
27                        NaN                        NaN
28                        NaN                        NaN
29                        NaN                        NaN
30                        NaN                        NaN

[31 rows x 43 columns]>

In [33]:
print(patient_details.head())

         _id   firstName     lastName emailId gender alternateContact  \
0  T6hb630b3         Css                           M
1  T6h33b300      Lokesh                           M              NaN
2   TjhB4373       Shila          Das              M              NaN
3    6df4R5b     Bhavika  Ben Panchal              F              NaN
4   lK9hy06a  Raghu Viju                           M

                  birthDate         phrId chat customId   age ageGroup
0                       NaT           NaN  NaN      NaN   NaN   Senior
1 1996-05-16 18:30:00+00:00           NaN  NaN      NaN  28.0    Adult
2                       NaT  63b5hvy614d5  NaN      NaN   NaN   Senior
3 1988-04-24 14:30:00+00:00      644nig7y  NaN      NaN  36.0    Adult
4                       NaT           NaN  NaN      NaN   NaN   Senior

In [43]:
from collections import Counter

In [46]:
medicines_frozensets = [frozenset(med.items()) for med in medicines]

# Count the frequency of each medicine
medicine_counter = Counter(medicines_frozensets)

# Get the 3rd most common medicine
most_common = medicine_counter.most_common(3)
print(most_common[2] if len(most_common) > 2 else "Not enough data")

(frozenset({('durationIn', 'DAYS'), ('medicineNameStrengthType', ''), ('medicineName', 'D'), ('instruction', 'AFTER MEAL'), ('duration', '90'), ('frequency', '1-0-1'), ('isActive', False), ('medicineId', '612504')}), 4)

In [48]:

statuses = [med['status'] for med in df['consultationData_medicines']]

status_counter = Counter(statuses)

total_medicines = len(df['consultationData_medicines'])

active_percentage = (status_counter['active'] / total_medicines) * 100
inactive_percentage = (status_counter['inactive'] / total_medicines) * 100

print(f"{active_percentage:.2f}, {inactive_percentage:.2f}")

TypeError: list indices must be integers or slices, not str

In [49]:
def is_valid_indian_phone_number(phone_number):

    phone_number = phone_number.strip()

    if phone_number.startswith('+91'):
        phone_number = phone_number[3:]
    elif phone_number.startswith('91'):
        phone_number = phone_number[2:]

    if len(phone_number) == 10 and phone_number.isdigit():

        if phone_number.isdigit() and 6000000000 <= int(phone_number) <= 9999999999:
            return True
    return False

dataset = df

for record in dataset:
    record['isValidMobile'] = is_valid_indian_phone_number(record['phoneNumber'])

valid_count = sum(1 for record in dataset if record['isValidMobile'])

for record in dataset:
    print(record)

print(f"Number of valid phone numbers found: {valid_count}")

{'phoneNumber': '+919876787687', 'isValidMobile': True}
{'phoneNumber': '919877475896', 'isValidMobile': True}
{'phoneNumber': '+913454768688', 'isValidMobile': False}
{'phoneNumber': '9876787687', 'isValidMobile': True}
{'phoneNumber': '3454768688', 'isValidMobile': False}
{'phoneNumber': '57769666', 'isValidMobile': False}
Number of valid phone numbers found: 3

In [51]:
import numpy as np

In [ ]:
ages = np.array([patient_details['age'] for record in data])
medicines = np.array([df[''] for record in data])


correlation = np.corrcoef(ages, medicines)[0, 1]


print(f"{correlation:.2f}")